### ISSUE TITLE
[BUG] Creating anomaly detector stucks at initializing state

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/anomaly-detection#576] opened 2022-06-20 20:38 UTC
@eslam-gomaa commented on [Sat Jun 18 2022](https://github.com/opensearch-project/anomaly-detection/issues/577)

**Describe the bug**
Hi
I believe that this is not a bug, I'm just asking for guidance 

When creating anomaly detector, it stuck at the initializing state for many days !  (some stuck for infinity)
After a bit of investigation I found that this only happens when the index pattern used with the detector has very few events steam (due to the filter used with the detector)

Is there specific configuration I need to consider in my case ? 🤔 
 
```
GET _opendistro/_anomaly_detection/detectors/vmwCWoEBNq3GYhZRwdMX/_profile?_all
```

```
{
  "state" : "INIT",
  "total_size_in_bytes" : 0,
  "init_progress" : {
    "percentage" : "0%",
    "estimated_minutes_left" : 256,
    "needed_shingles" : 128
  },
  "total_entities" : 911,
  "active_entities" : 0
}
```

**To Reproduce**
Create an anomaly detectors on index pattern that has few events steam.

**Expected behavior**
The detector to finish initialization successfully and becomes "running"

**Plugins**
anomaly detection

```bash
GET _opendistro/_anomaly_detection/stats
```
```
{
  "anomaly_detectors_index_status" : "green",
  "anomaly_detection_state_status" : "green",
  "detector_count" : 19,
  "anomaly_detection_job_index_status" : "green",
  "models_checkpoint_index_status" : "green",
.....
```

**Screenshots**

![image](https://user-images.githubusercontent.com/33789516/174452434-7ef72917-df8b-4daf-aece-589ce094b34d.png)

#### sometimes to gets up to `2%`  and back to `0` again
![image](https://user-images.githubusercontent.com/33789516/174472561-e40d8c5c-e713-48e1-a120-c6221181b3b5.png)

![image](https://user-images.githubusercontent.com/33789516/174472582-299f7de2-c0f4-4a0c-b0c1-4ee491082fce.png)

**Host/Environment (please complete the following information):**
 - AWS Opensearch service with Elasticsearch 7.10.2

---

If more information is needed pls let me know

Thanks in advance

**Comment by kaituo** [comment] 2023-03-13 17:49
duplicate of https://github.com/opensearch-project/anomaly-detection/issues/577. Will address the issue there.

**Closed by kaituo** 2023-03-13 17:49 UTC
