### ISSUE TITLE
[BUG] CI failed on 1.2 branch

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#351] opened 2022-01-06 16:12 UTC
**Describe the bug**
Failing CI on 1.2 branch, https://github.com/opensearch-project/anomaly-detection/runs/4728982394?check_suite_focus=true, looks like something flaky because it succeeded in the PR.

**Expected behavior**
Reliably passing CI.

**Comment by amitgalitz** [comment] 2022-01-06 17:28
Just re-run workflow for the branch. The two tests that failed are ones we have previously documented on this issue: https://github.com/opensearch-project/anomaly-detection/issues/278. They aren't due to any code bug but rather flakey env. I will add this instance of failure to issue as well and make an effort to fix them. 

Will also update here if re-runbing workflow passes on this branch.

**Comment by amitgalitz** [comment] 2022-01-07 17:50
> Just re-run workflow for the branch. The two tests that failed are ones we have previously documented on this issue: #278. They aren't due to any code bug but rather flakey env. I will add this instance of failure to issue as well and make an effort to fix them.
> 
> Will also update here if re-running workflow passes on this branch.

Had to re-run workflow twice because another flaky test failed on second attempt. 1.2 branch is now passing all workflows. I have updated the issue with any flaky tests that showed up for the 1.2 branch and currently digging deeper to find root cause for all of them and actively trying to fix them. 
I will be closing this issue as it's covered in the issue mentioned above along with other flaky tests.

**Closed by amitgalitz** 2022-01-07 17:50 UTC
Labels: bug, Beta, untriaged
